### ISSUE TITLE
[Bug/FML]: Awful 1.20.1 lag spikes, more context below

### ISSUE THREAD

**Issue by Cixon** [Team-Resourceful/ResourcefulLib#7]
### Bug Description

I believe resourceful is disrupting my single player performance. Periodically, I'll drop a ton of FPS and when reviewing the logs, I notice this (see line 16,705)

### How to Reproduce?

(tested in sp using FML 47.1.3)
1. Install latest Argonauts, Cadmus, Prometheus and dependency.
2. Fire up a single player world
3. Browse around in creative
4. See debug after some time.

### Expected Behavior

Didn't expect performance dip in my sp experience.

### Version

forge-1.20.1-2.1.10

### Mod Loader Version

47.1.3

### Logs or additional context

https://gist.github.com/Cixon/32b61bab18b40d8828b0f786284b9e44

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Cixon** [comment]
[debug.txt](https://github.com/Team-Resourceful/ResourcefulLib/files/12425286/debug.txt)

oops. didn't realize that gist has a cap.

**Comment by ThatGravyBoat** [comment]
Nothing in there indicates resourceful lib causing you lag. I would suggest doing a proper profiling with something Spark

**Comment by Cixon** [comment]
> Nothing in there indicates resourceful lib causing you lag. I would suggest doing a proper profiling with something Spark

Can you provide a fix for this error at least? It's still bloat to the log

[24Aug2023 08:35:24.008] [ForkJoinPool.commonPool-worker-4/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent com/teamresourceful/resourcefullib/common/utils/SaveHandler for class earth/terrarium/prometheus/common/handlers/MuteHandler in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@67b64c45 on thread Thread[ForkJoinPool.commonPool-worker-4,4,SERVER]
[24Aug2023 08:35:24.008] [ForkJoinPool.commonPool-worker-4/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: com.teamresourceful.resourcefullib.common.utils.SaveHandler
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar:6.0.5+6.0.5+master.eb8e549b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at earth.terrarium.prometheus.forge.PrometheusForge.onChatMessage(PrometheusForge.java:44) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar:?]
	at net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:391) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.lambda$getServerChatSubmittedDecorator$0(ForgeHooks.java:401) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by ThatGravyBoat** [comment]
You have a mod screwing up the class loading I have no idea which one but that class exists and is used in many places through out multiple mods without any issues

**Comment by Cixon** [comment]
> You have a mod screwing up the class loading I have no idea which one but that class exists and is used in many places through out multiple mods without any issues

I’ll have to do some diagnostics. I think it might be one of the performance mods but I’m unsure. Thanks for reading the hieroglyphics for me, I’m not a coder.
